// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DAL.Migrations
{
    [DbContext(typeof(ConnectorContext))]
    partial class ConnectorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DAL.Model.TConnector", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<bool>("Status");

                    b.HasKey("ID");

                    b.ToTable("T_CONNECTOR");
                });

            modelBuilder.Entity("DAL.Model.TDatasource", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ConnectorId");

                    b.Property<string>("Name");

                    b.Property<bool>("Status");

                    b.HasKey("ID");

                    b.HasIndex("ConnectorId");

                    b.ToTable("T_DATASOURCE");
                });

            modelBuilder.Entity("DAL.Model.TDatasource", b =>
                {
                    b.HasOne("DAL.Model.TConnector", "Connector")
                        .WithMany("Datasources")
                        .HasForeignKey("ConnectorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
